project_id = "gcaelrgcmjpkibugcbva"

[functions.trigger-webhook]
verify_jwt = false

[functions.send-rsvp-confirmation]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-rsvp-sms]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.admin-update-subscription]
verify_jwt = true

[functions.send-rsvp-notification]
verify_jwt = false