export interface PremiumTemplateConfig {
  id: string;
  name: string;
  category: 'Wedding' | 'Baptism' | 'Party';
  type: 'wedding' | 'baptism' | 'party';
  mood: string;
  theme: 'luxury' | 'elegant' | 'modern' | 'romantic' | 'royal' | 'fun' | 'cute';
  title: string;
  subtitle?: string;
  names: string;
  backgroundImage: string;
  accentColor: string;
  secondaryColor: string;
  date?: string;
  venue?: string;
  description?: string;
  price: string;
}

export const premiumTemplates: PremiumTemplateConfig[] = [
  // WEDDING TEMPLATES (20)
  {
    id: 'wedding-1',
    name: 'Royal Romance',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Elegant & Luxurious',
    theme: 'royal',
    title: 'Our Forever Begins',
    subtitle: 'Join us in celebrating our love',
    names: 'Alexandra & Dimitris',
    backgroundImage: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1080&q=80',
    accentColor: '#C9A961',
    secondaryColor: '#2C1810',
    date: '2024-06-15',
    venue: 'Grand Palace Hotel',
    description: 'An elegant celebration of love and commitment',
    price: 'Premium'
  },
  {
    id: 'wedding-2',
    name: 'Garden Dreams',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Romantic & Natural',
    theme: 'romantic',
    title: 'Love in Bloom',
    subtitle: 'Celebrate with us in the garden',
    names: 'Maria & Nikos',
    backgroundImage: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1080&q=80',
    accentColor: '#E8B4B8',
    secondaryColor: '#4A5D4B',
    date: '2024-07-20',
    venue: 'Botanical Gardens',
    description: 'A romantic garden wedding surrounded by nature',
    price: 'Premium'
  },
  {
    id: 'wedding-3',
    name: 'Modern Elegance',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Contemporary & Chic',
    theme: 'modern',
    title: 'Together Forever',
    subtitle: 'A modern love story',
    names: 'Sofia & Andreas',
    backgroundImage: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1080&q=80',
    accentColor: '#000000',
    secondaryColor: '#FFFFFF',
    date: '2024-08-10',
    venue: 'City Loft Gallery',
    description: 'A sleek, modern celebration',
    price: 'Premium'
  },
  {
    id: 'wedding-4',
    name: 'Vintage Charm',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Nostalgic & Classic',
    theme: 'elegant',
    title: 'Timeless Love',
    subtitle: 'Celebrating our vintage romance',
    names: 'Elena & Kostas',
    backgroundImage: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1080&q=80',
    accentColor: '#D4A373',
    secondaryColor: '#5B4636',
    date: '2024-09-05',
    venue: 'Historic Manor',
    description: 'A timeless celebration with vintage elegance',
    price: 'Premium'
  },
  {
    id: 'wedding-5',
    name: 'Beach Paradise',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Tropical & Relaxed',
    theme: 'romantic',
    title: 'Waves of Love',
    subtitle: 'Say I do by the sea',
    names: 'Christina & Yannis',
    backgroundImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1080&q=80',
    accentColor: '#00A8CC',
    secondaryColor: '#F4E8C1',
    date: '2024-10-12',
    venue: 'Seaside Resort',
    description: 'A beautiful beach wedding at sunset',
    price: 'Premium'
  },
  {
    id: 'wedding-6',
    name: 'Rustic Romance',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Countryside & Warm',
    theme: 'elegant',
    title: 'Country Love',
    subtitle: 'A rustic celebration',
    names: 'Anna & Petros',
    backgroundImage: 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=1080&q=80',
    accentColor: '#8B4513',
    secondaryColor: '#F5DEB3',
    date: '2024-11-18',
    venue: 'Countryside Barn',
    description: 'Rustic charm meets romantic elegance',
    price: 'Premium'
  },
  {
    id: 'wedding-7',
    name: 'Crystal Elegance',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Glamorous & Sophisticated',
    theme: 'luxury',
    title: 'Sparkling Forever',
    subtitle: 'A glamorous celebration',
    names: 'Katerina & Stavros',
    backgroundImage: 'https://images.unsplash.com/photo-1522413452208-996ff3f3e740?w=1080&q=80',
    accentColor: '#C0C0C0',
    secondaryColor: '#1C1C1C',
    date: '2024-12-01',
    venue: 'Crystal Ballroom',
    description: 'Luxury and glamour for your special day',
    price: 'Premium'
  },
  {
    id: 'wedding-8',
    name: 'Boho Chic',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Free-spirited & Artistic',
    theme: 'romantic',
    title: 'Wild & Free',
    subtitle: 'A bohemian love story',
    names: 'Ioanna & Giorgos',
    backgroundImage: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=1080&q=80',
    accentColor: '#E07A5F',
    secondaryColor: '#3D405B',
    date: '2025-01-20',
    venue: 'Outdoor Field',
    description: 'Bohemian vibes for a unique celebration',
    price: 'Premium'
  },
  {
    id: 'wedding-9',
    name: 'Fairytale Castle',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Magical & Enchanting',
    theme: 'royal',
    title: 'Once Upon A Time',
    subtitle: 'Our fairytale begins',
    names: 'Vasiliki & Alexandros',
    backgroundImage: 'https://images.unsplash.com/photo-1519167758481-83f29da8a9d4?w=1080&q=80',
    accentColor: '#9B59B6',
    secondaryColor: '#FFD700',
    date: '2025-02-14',
    venue: 'Castle Estate',
    description: 'A magical fairytale wedding',
    price: 'Premium'
  },
  {
    id: 'wedding-10',
    name: 'Minimalist Love',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Simple & Pure',
    theme: 'modern',
    title: 'Simply Us',
    subtitle: 'Less is more',
    names: 'Dimitra & Michalis',
    backgroundImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1080&q=80',
    accentColor: '#2C3E50',
    secondaryColor: '#ECF0F1',
    date: '2025-03-10',
    venue: 'Modern Gallery',
    description: 'Minimalist elegance at its finest',
    price: 'Premium'
  },
  {
    id: 'wedding-11',
    name: 'Sunset Romance',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Warm & Intimate',
    theme: 'romantic',
    title: 'Golden Hour Love',
    subtitle: 'As the sun sets on our single lives',
    names: 'Panagiota & Dimitris',
    backgroundImage: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=1080&q=80',
    accentColor: '#FF6B6B',
    secondaryColor: '#FFE66D',
    date: '2025-04-22',
    venue: 'Hilltop Terrace',
    description: 'Celebrate love at golden hour',
    price: 'Premium'
  },
  {
    id: 'wedding-12',
    name: 'Lavender Fields',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Dreamy & Serene',
    theme: 'romantic',
    title: 'Fields of Love',
    subtitle: 'Love blooms in purple',
    names: 'Eleni & Panagiotis',
    backgroundImage: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=1080&q=80',
    accentColor: '#967BB6',
    secondaryColor: '#E6E6FA',
    date: '2025-05-18',
    venue: 'Lavender Farm',
    description: 'A dreamy lavender field wedding',
    price: 'Premium'
  },
  {
    id: 'wedding-13',
    name: 'Metropolitan Chic',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Urban & Stylish',
    theme: 'modern',
    title: 'City Lights Love',
    subtitle: 'Urban romance',
    names: 'Chrysa & Stratos',
    backgroundImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1080&q=80',
    accentColor: '#34495E',
    secondaryColor: '#F39C12',
    date: '2025-06-08',
    venue: 'Rooftop Venue',
    description: 'Stylish city wedding with skyline views',
    price: 'Premium'
  },
  {
    id: 'wedding-14',
    name: 'Winter Wonderland',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Magical & Frosty',
    theme: 'elegant',
    title: 'Snow & Love',
    subtitle: 'A winter fairytale',
    names: 'Despina & Konstantinos',
    backgroundImage: 'https://images.unsplash.com/photo-1482575832494-771f74bf6857?w=1080&q=80',
    accentColor: '#4A90E2',
    secondaryColor: '#FFFFFF',
    date: '2025-12-20',
    venue: 'Mountain Lodge',
    description: 'A magical winter wedding celebration',
    price: 'Premium'
  },
  {
    id: 'wedding-15',
    name: 'Spring Blossom',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Fresh & Joyful',
    theme: 'romantic',
    title: 'Blooming Love',
    subtitle: 'Spring into forever',
    names: 'Antigoni & Ioannis',
    backgroundImage: 'https://images.unsplash.com/photo-1458682625221-3a45f8a844c7?w=1080&q=80',
    accentColor: '#FFB6C1',
    secondaryColor: '#98D8C8',
    date: '2025-04-05',
    venue: 'Cherry Blossom Park',
    description: 'Celebrate spring with cherry blossoms',
    price: 'Premium'
  },
  {
    id: 'wedding-16',
    name: 'Starlit Night',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Mystical & Romantic',
    theme: 'elegant',
    title: 'Under the Stars',
    subtitle: 'A celestial celebration',
    names: 'Fotini & Apostolos',
    backgroundImage: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=1080&q=80',
    accentColor: '#191970',
    secondaryColor: '#FFD700',
    date: '2025-07-30',
    venue: 'Observatory Garden',
    description: 'Dance under the stars on your special night',
    price: 'Premium'
  },
  {
    id: 'wedding-17',
    name: 'Vineyard Romance',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Rustic & Elegant',
    theme: 'elegant',
    title: 'Wine & Roses',
    subtitle: 'Love aged to perfection',
    names: 'Theodora & Vassilis',
    backgroundImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1080&q=80',
    accentColor: '#722F37',
    secondaryColor: '#F4E4C1',
    date: '2025-09-15',
    venue: 'Estate Vineyard',
    description: 'Celebrate love in wine country',
    price: 'Premium'
  },
  {
    id: 'wedding-18',
    name: 'Tropical Paradise',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Exotic & Vibrant',
    theme: 'romantic',
    title: 'Island Love',
    subtitle: 'Paradise found',
    names: 'Kalliopi & Spyros',
    backgroundImage: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1080&q=80',
    accentColor: '#FF6F61',
    secondaryColor: '#00CED1',
    date: '2025-08-25',
    venue: 'Beach Resort',
    description: 'Tropical paradise wedding celebration',
    price: 'Premium'
  },
  {
    id: 'wedding-19',
    name: 'Art Deco Glam',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Vintage & Glamorous',
    theme: 'luxury',
    title: 'Roaring Romance',
    subtitle: '1920s elegance',
    names: 'Evangelia & Nikolaos',
    backgroundImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1080&q=80',
    accentColor: '#D4AF37',
    secondaryColor: '#000000',
    date: '2025-10-31',
    venue: 'Historic Theater',
    description: 'Step back in time with Art Deco glamour',
    price: 'Premium'
  },
  {
    id: 'wedding-20',
    name: 'Enchanted Forest',
    category: 'Wedding',
    type: 'wedding',
    mood: 'Whimsical & Natural',
    theme: 'romantic',
    title: 'Woodland Wonder',
    subtitle: 'Lost in the forest of love',
    names: 'Marianna & Christos',
    backgroundImage: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1080&q=80',
    accentColor: '#228B22',
    secondaryColor: '#DEB887',
    date: '2025-11-12',
    venue: 'Forest Clearing',
    description: 'An enchanted forest celebration',
    price: 'Premium'
  },

  // BAPTISM TEMPLATES (20)
  {
    id: 'baptism-1',
    name: 'Little Prince',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Royal & Elegant',
    theme: 'royal',
    title: 'A Royal Blessing',
    subtitle: 'Celebrating our little prince',
    names: 'Baby Alexandros',
    backgroundImage: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1080&q=80',
    accentColor: '#4169E1',
    secondaryColor: '#FFD700',
    date: '2024-06-20',
    venue: 'St. Nicholas Church',
    description: 'Join us for a royal baptism celebration',
    price: 'Premium'
  },
  {
    id: 'baptism-2',
    name: 'Little Princess',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Sweet & Delicate',
    theme: 'elegant',
    title: 'Princess Blessing',
    subtitle: 'Our little princess',
    names: 'Baby Maria',
    backgroundImage: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1080&q=80',
    accentColor: '#FFB6C1',
    secondaryColor: '#FFD700',
    date: '2024-07-15',
    venue: 'Holy Cross Church',
    description: 'A princess celebration',
    price: 'Premium'
  },
  {
    id: 'baptism-3',
    name: 'Teddy Bear Dreams',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Cute & Cuddly',
    theme: 'cute',
    title: 'Sweet Dreams',
    subtitle: 'Teddy bear blessings',
    names: 'Baby Nikos',
    backgroundImage: 'https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?w=1080&q=80',
    accentColor: '#8B4513',
    secondaryColor: '#FFF8DC',
    date: '2024-08-10',
    venue: 'St. George Church',
    description: 'Cozy teddy bear themed baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-4',
    name: 'Bunny Hop',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Playful & Adorable',
    theme: 'cute',
    title: 'Hop Into Blessings',
    subtitle: 'Our little bunny',
    names: 'Baby Sophia',
    backgroundImage: 'https://images.unsplash.com/photo-1585128792160-da3e6a46c61f?w=1080&q=80',
    accentColor: '#FFB6D9',
    secondaryColor: '#FFFFFF',
    date: '2024-09-05',
    venue: 'St. Anna Church',
    description: 'Adorable bunny themed celebration',
    price: 'Premium'
  },
  {
    id: 'baptism-5',
    name: 'Little Sailor',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Nautical & Fresh',
    theme: 'modern',
    title: 'Ahoy Little One',
    subtitle: 'Setting sail with blessings',
    names: 'Baby Dimitris',
    backgroundImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1080&q=80',
    accentColor: '#000080',
    secondaryColor: '#FFFFFF',
    date: '2024-10-12',
    venue: 'Seaside Chapel',
    description: 'Nautical themed baptism by the sea',
    price: 'Premium'
  },
  {
    id: 'baptism-6',
    name: 'Garden Fairy',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Magical & Whimsical',
    theme: 'romantic',
    title: 'Fairy Blessings',
    subtitle: 'Our little fairy',
    names: 'Baby Eleni',
    backgroundImage: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1080&q=80',
    accentColor: '#E8B4F1',
    secondaryColor: '#98FB98',
    date: '2024-11-18',
    venue: 'Garden Chapel',
    description: 'Magical fairy garden baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-7',
    name: 'Cloud Nine',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Dreamy & Soft',
    theme: 'elegant',
    title: 'Heavenly Blessings',
    subtitle: 'Floating on cloud nine',
    names: 'Baby Katerina',
    backgroundImage: 'https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=1080&q=80',
    accentColor: '#B0E0E6',
    secondaryColor: '#FFFFFF',
    date: '2024-12-01',
    venue: 'St. Dimitrios Church',
    description: 'Dreamy cloud themed baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-8',
    name: 'Rainbow Joy',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Colorful & Happy',
    theme: 'fun',
    title: 'Rainbow Blessings',
    subtitle: 'Our colorful miracle',
    names: 'Baby Andreas',
    backgroundImage: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1080&q=80',
    accentColor: '#FF6B9D',
    secondaryColor: '#C5A3FF',
    date: '2025-01-20',
    venue: 'Holy Trinity Church',
    description: 'Vibrant rainbow baptism celebration',
    price: 'Premium'
  },
  {
    id: 'baptism-9',
    name: 'Little Angel',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Pure & Blessed',
    theme: 'elegant',
    title: 'Angelic Blessing',
    subtitle: 'Our little angel',
    names: 'Baby Christina',
    backgroundImage: 'https://images.unsplash.com/photo-1519340333755-56e9c1d82261?w=1080&q=80',
    accentColor: '#FFFFFF',
    secondaryColor: '#FFD700',
    date: '2025-02-14',
    venue: 'St. Michael Church',
    description: 'Pure angelic baptism celebration',
    price: 'Premium'
  },
  {
    id: 'baptism-10',
    name: 'Butterfly Dreams',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Delicate & Beautiful',
    theme: 'romantic',
    title: 'Butterfly Kisses',
    subtitle: 'Transformed by love',
    names: 'Baby Ioanna',
    backgroundImage: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=1080&q=80',
    accentColor: '#DA70D6',
    secondaryColor: '#F0E68C',
    date: '2025-03-10',
    venue: 'Garden Chapel',
    description: 'Beautiful butterfly themed baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-11',
    name: 'Star Baby',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Celestial & Bright',
    theme: 'elegant',
    title: 'Shining Star',
    subtitle: 'Our bright little star',
    names: 'Baby Giorgos',
    backgroundImage: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=1080&q=80',
    accentColor: '#FFD700',
    secondaryColor: '#191970',
    date: '2025-04-22',
    venue: 'St. Constantine Church',
    description: 'Celestial star themed baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-12',
    name: 'Elephant Joy',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Fun & Playful',
    theme: 'cute',
    title: 'Elephant Blessings',
    subtitle: 'Big love for our little one',
    names: 'Baby Panagiotis',
    backgroundImage: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=1080&q=80',
    accentColor: '#708090',
    secondaryColor: '#FFE4B5',
    date: '2025-05-18',
    venue: 'St. Paul Church',
    description: 'Adorable elephant themed baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-13',
    name: 'Flower Garden',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Fresh & Natural',
    theme: 'romantic',
    title: 'Blooming Blessings',
    subtitle: 'Our little flower',
    names: 'Baby Vasiliki',
    backgroundImage: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1080&q=80',
    accentColor: '#FF69B4',
    secondaryColor: '#98FB98',
    date: '2025-06-08',
    venue: 'Botanical Garden Chapel',
    description: 'Fresh flower garden baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-14',
    name: 'Moon & Stars',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Peaceful & Dreamy',
    theme: 'elegant',
    title: 'Moonlight Miracle',
    subtitle: 'Under the stars',
    names: 'Baby Konstantinos',
    backgroundImage: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=1080&q=80',
    accentColor: '#F0E68C',
    secondaryColor: '#191970',
    date: '2025-07-30',
    venue: 'Evening Chapel',
    description: 'Peaceful moonlit baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-15',
    name: 'Little Lion',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Bold & Brave',
    theme: 'fun',
    title: 'Brave Heart',
    subtitle: 'Our little lion',
    names: 'Baby Apostolos',
    backgroundImage: 'https://images.unsplash.com/photo-1456926631375-92c8ce872def?w=1080&q=80',
    accentColor: '#DAA520',
    secondaryColor: '#8B4513',
    date: '2025-08-25',
    venue: 'St. Luke Church',
    description: 'Bold lion themed baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-16',
    name: 'Sweet Dreams',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Gentle & Calm',
    theme: 'elegant',
    title: 'Dream Come True',
    subtitle: 'Sweet baby dreams',
    names: 'Baby Despina',
    backgroundImage: 'https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=1080&q=80',
    accentColor: '#E6E6FA',
    secondaryColor: '#FFB6C1',
    date: '2025-09-15',
    venue: 'St. Barbara Church',
    description: 'Gentle sweet dreams baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-17',
    name: 'Ocean Waves',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Fresh & Serene',
    theme: 'modern',
    title: 'Ocean Blessings',
    subtitle: 'Waves of love',
    names: 'Baby Spyros',
    backgroundImage: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1080&q=80',
    accentColor: '#00CED1',
    secondaryColor: '#F0F8FF',
    date: '2025-10-05',
    venue: 'Seaside Chapel',
    description: 'Fresh ocean themed baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-18',
    name: 'Vintage Lace',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Classic & Timeless',
    theme: 'elegant',
    title: 'Timeless Blessing',
    subtitle: 'Classic elegance',
    names: 'Baby Fotini',
    backgroundImage: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1080&q=80',
    accentColor: '#F5F5DC',
    secondaryColor: '#D2B48C',
    date: '2025-11-12',
    venue: 'Historic Church',
    description: 'Timeless vintage lace baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-19',
    name: 'Circus Fun',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Playful & Festive',
    theme: 'fun',
    title: 'Circus Celebration',
    subtitle: 'The show begins',
    names: 'Baby Theodoros',
    backgroundImage: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1080&q=80',
    accentColor: '#FF0000',
    secondaryColor: '#FFD700',
    date: '2025-12-01',
    venue: 'Party Hall',
    description: 'Fun circus themed baptism',
    price: 'Premium'
  },
  {
    id: 'baptism-20',
    name: 'Sunshine Baby',
    category: 'Baptism',
    type: 'baptism',
    mood: 'Bright & Cheerful',
    theme: 'fun',
    title: 'Sunshine Blessing',
    subtitle: 'You are my sunshine',
    names: 'Baby Marianna',
    backgroundImage: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1080&q=80',
    accentColor: '#FFD700',
    secondaryColor: '#FFA500',
    date: '2025-12-20',
    venue: 'Sunny Chapel',
    description: 'Bright sunshine baptism',
    price: 'Premium'
  },

  // PARTY TEMPLATES (20)
  {
    id: 'party-1',
    name: 'Neon Nights',
    category: 'Party',
    type: 'party',
    mood: 'Electric & Vibrant',
    theme: 'modern',
    title: 'Neon Party',
    subtitle: 'Light up the night',
    names: 'DJ Night Party',
    backgroundImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1080&q=80',
    accentColor: '#00FF00',
    secondaryColor: '#FF00FF',
    date: '2024-12-31',
    venue: 'Club Downtown',
    description: 'Electric neon party night',
    price: 'Premium'
  },
  {
    id: 'party-2',
    name: 'Gold Glam',
    category: 'Party',
    type: 'party',
    mood: 'Luxurious & Sophisticated',
    theme: 'luxury',
    title: 'Golden Celebration',
    subtitle: 'Elegance in gold',
    names: 'VIP Gala',
    backgroundImage: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=1080&q=80',
    accentColor: '#FFD700',
    secondaryColor: '#000000',
    date: '2025-01-15',
    venue: 'Grand Ballroom',
    description: 'Luxurious gold themed party',
    price: 'Premium'
  },
  {
    id: 'party-3',
    name: 'Tropical Vibes',
    category: 'Party',
    type: 'party',
    mood: 'Fun & Exotic',
    theme: 'fun',
    title: 'Tropical Paradise',
    subtitle: 'Island party time',
    names: 'Summer Bash',
    backgroundImage: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1080&q=80',
    accentColor: '#00CED1',
    secondaryColor: '#FF6347',
    date: '2025-06-21',
    venue: 'Beach Club',
    description: 'Tropical island party',
    price: 'Premium'
  },
  {
    id: 'party-4',
    name: 'Black & White Ball',
    category: 'Party',
    type: 'party',
    mood: 'Classic & Elegant',
    theme: 'elegant',
    title: 'Monochrome Magic',
    subtitle: 'Black tie elegance',
    names: 'Elegant Soirée',
    backgroundImage: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1080&q=80',
    accentColor: '#000000',
    secondaryColor: '#FFFFFF',
    date: '2025-02-14',
    venue: 'Crystal Hall',
    description: 'Classic black and white ball',
    price: 'Premium'
  },
  {
    id: 'party-5',
    name: 'Masquerade Mystery',
    category: 'Party',
    type: 'party',
    mood: 'Mysterious & Elegant',
    theme: 'luxury',
    title: 'Mask & Mystery',
    subtitle: 'Unveil the night',
    names: 'Masquerade Ball',
    backgroundImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1080&q=80',
    accentColor: '#800080',
    secondaryColor: '#FFD700',
    date: '2025-10-31',
    venue: 'Mansion Estate',
    description: 'Mysterious masquerade ball',
    price: 'Premium'
  },
  {
    id: 'party-6',
    name: 'Retro 80s',
    category: 'Party',
    type: 'party',
    mood: 'Nostalgic & Fun',
    theme: 'fun',
    title: 'Back to the 80s',
    subtitle: 'Totally rad party',
    names: '80s Revival',
    backgroundImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1080&q=80',
    accentColor: '#FF00FF',
    secondaryColor: '#00FFFF',
    date: '2025-03-22',
    venue: 'Retro Club',
    description: 'Totally rad 80s party',
    price: 'Premium'
  },
  {
    id: 'party-7',
    name: 'Garden Soiree',
    category: 'Party',
    type: 'party',
    mood: 'Elegant & Natural',
    theme: 'elegant',
    title: 'Garden Party',
    subtitle: 'Under the stars',
    names: 'Evening Garden Party',
    backgroundImage: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=1080&q=80',
    accentColor: '#228B22',
    secondaryColor: '#FFB6C1',
    date: '2025-05-10',
    venue: 'Botanical Gardens',
    description: 'Elegant garden party',
    price: 'Premium'
  },
  {
    id: 'party-8',
    name: 'Casino Royale',
    category: 'Party',
    type: 'party',
    mood: 'Sophisticated & Thrilling',
    theme: 'luxury',
    title: 'Casino Night',
    subtitle: 'Roll the dice',
    names: 'Casino Party',
    backgroundImage: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=1080&q=80',
    accentColor: '#DC143C',
    secondaryColor: '#000000',
    date: '2025-11-20',
    venue: 'Casino Venue',
    description: 'Thrilling casino themed party',
    price: 'Premium'
  },
  {
    id: 'party-9',
    name: 'Boho Festival',
    category: 'Party',
    type: 'party',
    mood: 'Free-spirited & Artistic',
    theme: 'fun',
    title: 'Boho Bash',
    subtitle: 'Festival vibes',
    names: 'Music Festival Party',
    backgroundImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1080&q=80',
    accentColor: '#E07A5F',
    secondaryColor: '#3D405B',
    date: '2025-07-15',
    venue: 'Outdoor Field',
    description: 'Boho festival party',
    price: 'Premium'
  },
  {
    id: 'party-10',
    name: 'Great Gatsby',
    category: 'Party',
    type: 'party',
    mood: 'Roaring 20s Glam',
    theme: 'luxury',
    title: 'Gatsby Gala',
    subtitle: '1920s elegance',
    names: 'Art Deco Party',
    backgroundImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1080&q=80',
    accentColor: '#D4AF37',
    secondaryColor: '#000000',
    date: '2025-04-12',
    venue: 'Historic Hotel',
    description: 'Roaring 20s Gatsby party',
    price: 'Premium'
  },
  {
    id: 'party-11',
    name: 'Hollywood Premiere',
    category: 'Party',
    type: 'party',
    mood: 'Glamorous & Star-studded',
    theme: 'luxury',
    title: 'Red Carpet Night',
    subtitle: 'Hollywood glamour',
    names: 'Oscar Party',
    backgroundImage: 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=1080&q=80',
    accentColor: '#FF0000',
    secondaryColor: '#FFD700',
    date: '2025-02-28',
    venue: 'Theater Hall',
    description: 'Glamorous Hollywood party',
    price: 'Premium'
  },
  {
    id: 'party-12',
    name: 'Moroccan Nights',
    category: 'Party',
    type: 'party',
    mood: 'Exotic & Mystical',
    theme: 'elegant',
    title: 'Arabian Nights',
    subtitle: 'Moroccan magic',
    names: 'Exotic Party',
    backgroundImage: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1080&q=80',
    accentColor: '#B8860B',
    secondaryColor: '#8B0000',
    date: '2025-09-30',
    venue: 'Moroccan Lounge',
    description: 'Exotic Moroccan themed party',
    price: 'Premium'
  },
  {
    id: 'party-13',
    name: 'Winter Wonderland',
    category: 'Party',
    type: 'party',
    mood: 'Magical & Festive',
    theme: 'elegant',
    title: 'Ice Palace Party',
    subtitle: 'Winter magic',
    names: 'Holiday Celebration',
    backgroundImage: 'https://images.unsplash.com/photo-1482575832494-771f74bf6857?w=1080&q=80',
    accentColor: '#4A90E2',
    secondaryColor: '#FFFFFF',
    date: '2025-12-15',
    venue: 'Snow Lodge',
    description: 'Magical winter wonderland party',
    price: 'Premium'
  },
  {
    id: 'party-14',
    name: 'Disco Fever',
    category: 'Party',
    type: 'party',
    mood: 'Funky & Groovy',
    theme: 'fun',
    title: '70s Disco Night',
    subtitle: 'Boogie wonderland',
    names: 'Disco Party',
    backgroundImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1080&q=80',
    accentColor: '#FF1493',
    secondaryColor: '#FFD700',
    date: '2025-08-08',
    venue: 'Disco Club',
    description: 'Groovy 70s disco party',
    price: 'Premium'
  },
  {
    id: 'party-15',
    name: 'Carnival Celebration',
    category: 'Party',
    type: 'party',
    mood: 'Festive & Colorful',
    theme: 'fun',
    title: 'Carnival Madness',
    subtitle: 'Festival fun',
    names: 'Carnival Party',
    backgroundImage: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1080&q=80',
    accentColor: '#FF6B9D',
    secondaryColor: '#FFD700',
    date: '2025-02-25',
    venue: 'Festival Grounds',
    description: 'Colorful carnival celebration',
    price: 'Premium'
  },
  {
    id: 'party-16',
    name: 'Champagne Dreams',
    category: 'Party',
    type: 'party',
    mood: 'Luxurious & Bubbly',
    theme: 'luxury',
    title: 'Champagne Toast',
    subtitle: 'Sparkle & shine',
    names: 'New Year Celebration',
    backgroundImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1080&q=80',
    accentColor: '#D4AF37',
    secondaryColor: '#F0E68C',
    date: '2025-12-31',
    venue: 'Grand Hotel',
    description: 'Luxurious champagne party',
    price: 'Premium'
  },
  {
    id: 'party-17',
    name: 'Beach Bonfire',
    category: 'Party',
    type: 'party',
    mood: 'Casual & Warm',
    theme: 'fun',
    title: 'Bonfire Night',
    subtitle: 'Beach party vibes',
    names: 'Summer Beach Party',
    backgroundImage: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1080&q=80',
    accentColor: '#FF4500',
    secondaryColor: '#F4A460',
    date: '2025-07-04',
    venue: 'Sandy Beach',
    description: 'Warm beach bonfire party',
    price: 'Premium'
  },
  {
    id: 'party-18',
    name: 'Enchanted Forest',
    category: 'Party',
    type: 'party',
    mood: 'Mystical & Magical',
    theme: 'elegant',
    title: 'Forest Fantasy',
    subtitle: 'Woodland magic',
    names: 'Fairy Tale Party',
    backgroundImage: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=1080&q=80',
    accentColor: '#228B22',
    secondaryColor: '#FFD700',
    date: '2025-10-15',
    venue: 'Forest Clearing',
    description: 'Mystical enchanted forest party',
    price: 'Premium'
  },
  {
    id: 'party-19',
    name: 'Space Odyssey',
    category: 'Party',
    type: 'party',
    mood: 'Futuristic & Cosmic',
    theme: 'modern',
    title: 'Cosmic Party',
    subtitle: 'Journey to the stars',
    names: 'Space Party',
    backgroundImage: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=1080&q=80',
    accentColor: '#4B0082',
    secondaryColor: '#00CED1',
    date: '2025-11-11',
    venue: 'Observatory',
    description: 'Futuristic space themed party',
    price: 'Premium'
  },
  {
    id: 'party-20',
    name: 'Parisian Chic',
    category: 'Party',
    type: 'party',
    mood: 'Sophisticated & Romantic',
    theme: 'elegant',
    title: 'Parisian Soirée',
    subtitle: 'C\'est magnifique',
    names: 'French Party',
    backgroundImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1080&q=80',
    accentColor: '#000000',
    secondaryColor: '#FFB6C1',
    date: '2025-05-01',
    venue: 'French Bistro',
    description: 'Chic Parisian style party',
    price: 'Premium'
  }
];
